name: flutter_app
description: A Flutter project by Giovanni Petito

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  http: ^0.12.2
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.12+4
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1
  firebase_auth: ^0.20.1
  google_sign_in: ^4.5.3
  firebase_crashlytics: ^0.4.0+1
  firebase_core_platform_interface: ^3.0.1
  firebase_messaging: ^8.0.0-dev.15
  flutter_local_notifications: ^3.0.0
  device_info: ^1.0.0
  intl: ^0.16.1
  webview_flutter: ^0.3.14+1
  url_launcher: ^5.4.11
  image_sequence_animator: ^1.0.10
  fluttertoast: ^3.1.0
  permission: ^0.1.7
  flutter_multi_carousel: ^1.0.3
  shape_of_view: ^1.0.2

  audioplayers: ^0.17.1
  font_awesome_flutter: ^8.4.0
  geolocator: ^6.2.0
  flutter_spinkit: ^3.1.0
  animated_text_kit: ^1.3.0
  animations: ^1.1.2
  flutter_sequence_animation: ^3.0.1
  avatar_glow: ^1.2.0
  flutter_snake_navigationbar: ^0.4.4
  permission_handler: ^5.0.1+1

dev_dependencies:

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf